In [95]:
import numpy as np
import pandas as pd

In [138]:
train_data = pd.read_csv("encrypted/train_data.csv")

In [149]:
train_data

         MODE POWER   AMPS  VOLTS     TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347   66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412  -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979   40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754  -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955   37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...      ...  ...    ...    ...     ...
995      auto   low  0.350  4.257  274.581    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128  -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418  201.560    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291  -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538  -32.986    C  0.075  0.840  -0.379

[1000 rows x 9 columns]

In [151]:
df_cleaned = train_data.dropna()

In [152]:
df_cleaned = df_cleaned.drop(index = df_cleaned.loc[(df_cleaned['AMPS'] > 1) | (df_cleaned['AMPS'] < 0)].index)

In [153]:
df_cleaned = df_cleaned.drop(index = df_cleaned.loc[(df_cleaned['VOLTS'] > 8.7) | (df_cleaned['VOLTS'] < 0.02)].index)

In [154]:
df_cleaned = df_cleaned.drop(index = df_cleaned.loc[(df_cleaned['DELTA'] > 1) | (df_cleaned['DELTA'] < -1)].index)

In [155]:
df_cleaned = df_cleaned.drop(index = df_cleaned.loc[(df_cleaned['OUTPUT'] > 9.3) & (df_cleaned['OUTPUT'] < -8.4)].index)

In [156]:
df_cleaned = df_cleaned.drop(index = df_cleaned.loc[(df_cleaned['GAMMA'] > 2) & (df_cleaned['GAMMA'] < -2)].index)

In [157]:
df_cleaned = df_cleaned.drop(index = df_cleaned.loc[(df_cleaned['TEMP'] > 373.15) & (df_cleaned['TEMP'] < -100)].index)

In [158]:
df_cleaned

         MODE POWER   AMPS  VOLTS     TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347   66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412  -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979   40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754  -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955   37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...      ...  ...    ...    ...     ...
995      auto   low  0.350  4.257  274.581    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128  -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418  201.560    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291  -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538  -32.986    C  0.075  0.840  -0.379

[971 rows x 9 columns]

In [278]:
d = df_cleaned.copy()#loc[df_cleaned['UNIT'] == 'K']

def kelvin_to_celsius(kelvin):
    return kelvin - 273.15

def convert_to_celsius(row):
    if(row['UNIT'] == 'K'):
        return kelvin_to_celsius(row['TEMP'])
    elif(row['UNIT'] == 'C'):
        return row['TEMP']
    return row['TEMP']

In [279]:
d['TEMP'] = d.apply(convert_to_celsius, axis = 1)

In [280]:
kelvin_column = d.loc[(d['UNIT'] == 'K')]['TEMP']
somme = kelvin_column.sum()
mean = somme / len(kelvin_column)
ecart_type = kelvin_column.std()
print('moyenne ', mean)
print('ecart-type ', ecart_type)

moyenne  -0.6903755656108361
ecart-type  47.71908880263499

In [281]:
d

         MODE POWER   AMPS  VOLTS     TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347   66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412  -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979   40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754  -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955   37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...      ...  ...    ...    ...     ...
995      auto   low  0.350  4.257    1.431    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128  -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418  201.560    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291  -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538  -32.986    C  0.075  0.840  -0.379

[971 rows x 9 columns]

In [276]:
df_cleaned

         MODE POWER   AMPS  VOLTS     TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347   66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412  -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979   40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754  -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955   37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...      ...  ...    ...    ...     ...
995      auto   low  0.350  4.257  274.581    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128  -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418  201.560    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291  -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538  -32.986    C  0.075  0.840  -0.379

[971 rows x 9 columns]

In [259]:
min_unknow = df_cleaned.loc[(df_cleaned['UNIT'] != 'K') & (df_cleaned['UNIT'] != 'C')]['TEMP'].min()
max_unknow = df_cleaned.loc[(df_cleaned['UNIT'] != 'K') & (df_cleaned['UNIT'] != 'C')]['TEMP'].max()
print("Max = ", max_unknow)
print("Min = ", min_unknow)

Max =  362.996
Min =  -100.0

In [256]:
min_c = df_cleaned.loc[(df_cleaned['UNIT'] == 'C')]['TEMP'].min()
max_c = df_cleaned.loc[(df_cleaned['UNIT'] == 'C')]['TEMP'].max()
print("Max = ", max_c)
print("Min = ", min_c)

Max =  100.0
Min =  -100.0

In [257]:
min_k = df_cleaned.loc[(df_cleaned['UNIT'] == 'K')]['TEMP'].min()
max_k = df_cleaned.loc[(df_cleaned['UNIT'] == 'K')]['TEMP'].max()
print("Max = ", max_k)
print("Min = ", min_k)

Max =  373.15
Min =  173.15

In [267]:
unk_data = df_cleaned.loc[(df_cleaned['UNIT'] != 'K') & (df_cleaned['UNIT'] != 'C')]

In [268]:
unk_data.loc[(unk_data['TEMP'] > 100) & (unk_data['TEMP'] < 173.15)]

Empty DataFrame
Columns: [MODE, POWER, AMPS, VOLTS, TEMP, UNIT, DELTA, GAMMA, OUTPUT]
Index: []

In [288]:
def convert_unk_data(row):
    if(row['UNIT'] != 'K' and row['UNIT'] != 'C'):
        if(row['TEMP'] > 100):
            return row['TEMP'] - 273.15
    return row['TEMP']

In [289]:
rectified_unit = d.copy()

In [290]:
rectified_unit['TEMP'] = rectified_unit.apply(convert_unk_data, axis = 1)

In [291]:
rectified_unit

         MODE POWER   AMPS  VOLTS    TEMP UNIT  DELTA  GAMMA  OUTPUT
0    REDACTED  high  0.585  4.347  66.812    C -0.659 -0.527   3.749
1        beam   low  0.687  2.412 -17.044    C  0.508 -0.371  -1.062
2    REDACTED   low  0.888  2.979  40.918    C  0.600  1.412   2.265
3        auto   low  0.114  0.754 -43.308    C -0.760 -0.109   1.847
4       burst  high  0.318  3.955  37.752    C -0.751  0.492   1.821
..        ...   ...    ...    ...     ...  ...    ...    ...     ...
995      auto   low  0.350  4.257   1.431    K  0.991 -0.335   2.466
996      beam   low  0.644  1.128 -27.707    C -0.529  0.034  -1.834
997     burst   low  0.887  1.418 -71.590    ?  0.729 -0.503  -0.188
998  REDACTED   low  0.323  0.291 -17.162    C -0.120  0.524   0.081
999      beam  high  0.344  2.538 -32.986    C  0.075  0.840  -0.379

[971 rows x 9 columns]